package org.omg.IOP;


/**
* org/omg/IOP/TransactionService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/8-2-build-windows-i586-cygwin/jdk8u251/737/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, March 12, 2020 6:33:49 AM UTC
*/

public interface TransactionService
{

  /**
     * Identifies a CDR encapsulation of the 
     * <code>CosTSInteroperation.PropogationContext</code> defined in 
     * <i>CORBAservices: Common Object Services Specifications.</i>
     */
  public static final int value = (int)(0L);
}
